// Adds rollup properties to the Volunteers DB so session counts are visible on
// each volunteer's row, rather than only inside the alert engine.
//
// Adds, if not already there:
//   Sessions hosted      count of the Groups rows where they are Host
//   Sessions co-hosted   count of the Groups rows where they are Co-host
//   Sessions shadowed    count of the Groups rows where they are Shadow
//   Last session hosted  latest Date across the Groups rows where they are Host
//
// The relation names on the Volunteers side are auto-generated by Notion, so
// this reads them off the Groups DB's dual_property rather than guessing.
//
// Caveat worth knowing: a rollup counts every linked row, including sessions
// whose title starts with [CANCELED]. The alert engine excludes those, so the
// numbers can differ by a few. The alert engine is the one that decides who
// gets nudged.
//
//   npm run setup:rollups -- --dry-run
//   npm run setup:rollups

import { requireEnv, optionalEnv } from "./_env.js";

const dryRun = process.argv.includes("--dry-run");

const token = requireEnv("NOTION_TOKEN");
const apiVersion = optionalEnv("NOTION_API_VERSION", "2022-06-28");
const groupsDbId = requireEnv("NOTION_GROUPS_DB_ID");
const volunteersDbId = requireEnv("NOTION_VOLUNTEERS_DB_ID");

interface NotionDatabase {
  id: string;
  properties: Record<string, PropSchema>;
}
interface PropSchema {
  id: string;
  name: string;
  type: string;
  relation?: {
    database_id: string;
    type?: "single_property" | "dual_property";
    dual_property?: { synced_property_name?: string; synced_property_id?: string };
  };
  rollup?: { relation_property_name?: string; rollup_property_name?: string; function?: string };
}

async function notion<T>(path: string, init: RequestInit = {}): Promise<T> {
  const res = await fetch(`https://api.notion.com/v1${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      "Notion-Version": apiVersion,
      "Content-Type": "application/json",
      ...(init.headers ?? {}),
    },
  });
  const body = await res.text();
  if (!res.ok) throw new Error(`Notion ${init.method ?? "GET"} ${path} → ${res.status}\n${body}`);
  return JSON.parse(body) as T;
}

// What we want, keyed by the Groups-side relation it rolls up.
const WANTED: Array<{ groupsRelation: string; rollupName: string; fn: "count" | "latest_date" }> = [
  { groupsRelation: "Host", rollupName: "Sessions hosted", fn: "count" },
  { groupsRelation: "Co-host", rollupName: "Sessions co-hosted", fn: "count" },
  { groupsRelation: "Shadow", rollupName: "Sessions shadowed", fn: "count" },
  { groupsRelation: "Host", rollupName: "Last session hosted", fn: "latest_date" },
];

async function main() {
  console.log(dryRun ? "DRY RUN — nothing will be written.\n" : "Applying rollups.\n");

  const groups = await notion<NotionDatabase>(`/databases/${groupsDbId}`);
  const volunteers = await notion<NotionDatabase>(`/databases/${volunteersDbId}`);

  // Map each Groups relation to the property Notion created on Volunteers.
  const backRelation = new Map<string, string>();
  for (const name of ["Host", "Co-host", "Shadow"]) {
    const p = groups.properties[name];
    if (!p || p.type !== "relation") {
      console.log(`  Groups."${name}" is missing or not a relation — skipping its rollups.`);
      continue;
    }
    if (p.relation?.type !== "dual_property") {
      console.log(
        `  Groups."${name}" is a ONE-WAY relation, so Volunteers has nothing to roll up.\n` +
          `    Fix: open the property in Notion and turn on "Show on Volunteers".`,
      );
      continue;
    }
    const synced = p.relation.dual_property?.synced_property_name;
    if (!synced || !volunteers.properties[synced]) {
      console.log(`  Groups."${name}" says its Volunteers-side property is "${synced}", which isn't there.`);
      continue;
    }
    backRelation.set(name, synced);
    console.log(`  Groups."${name}"  ↔  Volunteers."${synced}"`);
  }

  const changes: string[] = [];
  const skipped: string[] = [];
  const properties: Record<string, unknown> = {};

  for (const want of WANTED) {
    const rel = backRelation.get(want.groupsRelation);
    if (!rel) {
      skipped.push(`${want.rollupName} — no usable relation for ${want.groupsRelation}`);
      continue;
    }
    if (volunteers.properties[want.rollupName]) {
      skipped.push(`${want.rollupName} already exists`);
      continue;
    }
    properties[want.rollupName] = {
      rollup: {
        relation_property_name: rel,
        rollup_property_name: "Date",
        function: want.fn,
      },
    };
    changes.push(`Volunteers: add "${want.rollupName}" (${want.fn} over ${rel})`);
  }

  if (changes.length && !dryRun) {
    await notion(`/databases/${volunteersDbId}`, {
      method: "PATCH",
      body: JSON.stringify({ properties }),
    });
  }

  console.log("\n── Summary ──");
  for (const s of skipped) console.log(`  skipped      ${s}`);
  for (const c of changes) console.log(`  ${dryRun ? "would do    " : "done        "} ${c}`);
  if (!changes.length) console.log("  Nothing to change.");
  else if (!dryRun) {
    console.log(
      `\nNote: these count every linked session, including ones titled [CANCELED].\n` +
        `The alert engine excludes those, so its numbers can be slightly lower.`,
    );
  }
}

main().catch((err) => {
  console.error(`\n${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
